// Home page of the app.
// Currently a placeholder "building" screen shown while the app is generated.
// Replace this file with your actual app UI. Do not delete it to use some other file as homepage. Simply replace the entire contents of this file.

import Head from "next/head";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Building your app - Lumaveno</title>
        <meta name="description" content="Your application is being generated by Lumaveno." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col items-center justify-center bg-[#08090a] text-[#f5f5f4] p-6 overflow-hidden relative">
        <div
          className="pointer-events-none absolute inset-x-0 top-0 h-64 opacity-60"
          style={{
            background:
              "radial-gradient(60% 100% at 50% 0%, rgba(239, 255, 10, 0.07) 0%, rgba(239, 255, 10, 0) 100%)",
          }}
        />

        <header className="absolute top-8 left-1/2 -translate-x-1/2 flex items-center gap-2 select-none">
          <span className="inline-block w-2 h-2 rounded-full bg-[#efff0a]" />
          <span className="text-sm font-medium tracking-[0.18em] uppercase text-[#f5f5f4]/80">
            Lumaveno
          </span>
        </header>

        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: "easeOut" }}
          className="text-center space-y-8 relative z-10"
        >
          <div className="space-y-4">
            <h1 className="text-4xl md:text-6xl font-display font-semibold text-balance leading-tight">
              Building your app<span className="text-[#efff0a]">.</span>
            </h1>
            <p className="text-base md:text-lg text-[#f5f5f4]/60 max-w-md mx-auto text-pretty">
              The first version is being written right now. This preview
              updates on its own — no need to reload.
            </p>
          </div>

          <div className="mx-auto w-56 h-px bg-white/10 relative overflow-hidden rounded-full">
            <motion.div
              className="absolute inset-y-0 w-20 bg-[#efff0a]"
              animate={{ left: ["-30%", "110%"] }}
              transition={{ duration: 1.6, repeat: Infinity, ease: "easeInOut" }}
            />
          </div>
        </motion.div>

        <footer className="absolute bottom-8 text-center text-sm text-[#f5f5f4]/40">
          <p>Powered by Lumaveno</p>
        </footer>
      </main>
    </>
  );
}
